export const ADD_COUNTER = 'ADD_COUNTER'
export const DELETE_COUNTER = 'DELETE_COUNTER'
export const INCREMENT_COUNTER_VALUE = 'INCREMENT_COUNTER_VALUE'
export const DECREMENT_COUNTER_VALUE = 'DECREMENT_COUNTER_VALUE'